### ISSUE TITLE
Prisma ORM parse failed

### ISSUE THREAD

**Issue by ludufre** [sindilevich/connection-string-parser#8]
Hi.

If the field password have @ the parser return an empty Object.

Prisma ORM allows @ at the password part. I.e.: `mysql://root:123@@127.0.0.1/test`

I'm not sure if this behavior is expected despite Prisma ORM being able to interpret it, I don't know if this would be correct.

**Comment by sindilevich** [comment]
Thank you, @ludufre, for reaching out!

It appears that the `@` sign is a reserved character that serves as a delimiter at the end of the `userinfo` part of a URI (https://www.rfc-editor.org/rfc/rfc3986#section-3.2.1).

As such, it cannot participate, unencoded, as part of the `userinfo` itself.

You can `percent-encode` your password, if it contains the `@` or any other reserved character, as per the specification: _If data for a URI component would conflict with a reserved character's purpose as a delimiter, then the conflicting data must be percent-encoded before the URI is formed._ (https://www.rfc-editor.org/rfc/rfc3986#section-2.2).

Otherwise, your sample URI isn't a valid one.
